name = "LinLogQuantization"
uuid = "44354dd6-1ce2-4e80-a0fb-98a3a2b05088"
authors = ["Milan <milankloewer@gmx.de> and contributors"]
version = "0.1.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
StatsBase = "0.30, 0.31, 0.32, 0.33"
BitIntegers = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
