name = "LinLogQuantization"
uuid = "44354dd6-1ce2-4e80-a0fb-98a3a2b05088"
authors = ["Milan <milankloewer@gmx.de> and contributors"]
version = "0.2.2"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"

[compat]
BitIntegers = "0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
